# Generated by Django 2.2.3 on 2019-07-27 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField()),
                ('type', models.CharField(max_length=16)),
                ('activation_time', models.DateField(blank=True, null=True)),
                ('expired_time', models.TimeField(blank=True, null=True)),
                ('expired_date', models.DateField(blank=True, null=True)),
                ('target_name', models.CharField(blank=True, default='', max_length=255)),
                ('filter_lbs', models.BooleanField()),
                ('sim_card_no', models.CharField(blank=True, default='', max_length=255)),
                ('license_plate_no', models.CharField(blank=True, default='', max_length=255)),
                ('phone_no', models.CharField(blank=True, default='', max_length=255)),
                ('fuel_per_100km', models.CharField(blank=True, default='', max_length=255)),
                ('contacts_no', models.CharField(blank=True, default='', max_length=255)),
                ('remark', models.TextField(blank=True, default='')),
                ('icon', models.CharField(choices=[('car', 'car'), ('truck', 'truck'), ('bus', 'bus'), ('bike', 'bike'), ('boat', 'boat'), ('person', 'person'), ('lock', 'lock')], default='car', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_customer', models.CharField(max_length=255)),
                ('login_account', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('roles', models.PositiveSmallIntegerField(choices=[(0, 'End User'), (1, 'Distributor')], default=0)),
                ('contacts', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('parent_customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking_app.Customer')),
            ],
        ),
    ]
