# Generated by Django 2.2.3 on 2019-07-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0002_auto_20190727_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='creation_date',
            field=models.DateField(auto_now=True),
        ),
    ]
